language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/build

script: ./script/build

# branch whitelist, only for GitHub Pages
branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # ускоряем установку html-proofer

sudo: false
