title: Конспект «Jekyll»
email: zinvapel@icloud.com
description: ""
excerpt_separator: <!--more-->
baseurl: "/c-jekyll"
url: "zinvapel.github.io"
twitter_username: zinvapel
github_username:  zinvapel

permalink: /:categories/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
future: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default-post"
      author: "zinvapel"
# highlighter: pygments does not support by GitHub Pages
