title: Конспект «Jekyll»
email: zinvapel@icloud.com
description: ""
excerpt_separator: <!--more-->
baseurl: "/c-jekyll"
url: "zinvapel.github.io"
twitter_username: zinvapel
github_username:  zinvapel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
